// React
import { useState } from 'react';

// Next
import type { NextPage } from 'next'
import Head from 'next/head'

// Libs
import classNames from 'classnames';

// Components
import { Wrapper } from '../components/Wrapper';
import { RGBAGenerator } from '../components/RGBAGenerator';
import { CurrentDate } from '../components/CurrentDate';
import { getCurrentHour, getFullYear } from '../utils/format';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>RGB Maker</title>
        <meta name="description" content="Generated by Guilherme Leandro Rolim" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        className="
          flex flex-col 
          items-center justify-center 
          bg-[#363940] 
          min-h-screen 
          px-2 sm:py-10 py-16"
        style={{
          background: `${getCurrentHour() < 18 ? "url(galaxy.jpg) no-repeat" : "url(galaxy-2.jpg) no-repeat"}`,
          backgroundSize: "cover",
        }}
      >
        <Wrapper>
          <h1 className="sm:text-5xl text-3xl text-center text-white font-bold mb-6">
            RGB Maker
          </h1>
          <CurrentDate />
          <RGBAGenerator />
        </Wrapper>
      </main>

      <footer className="bg-black px-2 py-16">
        <Wrapper>
          <p className="text-center text-white text-lg font-medium">
            &copy; {getFullYear()} Guilherme Leandro Rolim
          </p>
        </Wrapper>
      </footer>
    </>
  )
}

export default Home
